# Generated by Django 5.2.7 on 2025-11-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0006_remove_workoutsession_workout_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, max_length=200, null=True)),
                ('to_location', models.CharField(blank=True, max_length=200, null=True)),
                ('Coordinates', models.CharField(default='0,0', max_length=50)),
                ('WorkoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_reports', to='WorkoutPlan.workoutplan')),
            ],
        ),
    ]
