# Generated by Django 5.2.7 on 2025-12-02 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0007_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='Workout_list',
            field=models.CharField(choices=[('Pullup', 'Pullup'), ('Pushup', 'Pushup'), ('Plank', 'Plank'), ('Squat', 'Squat'), ('Lunges', 'Lunges'), ('Jumping Jacks', 'Jumping Jacks'), ('High Knees', 'High Knees'), ('Mountain Climbers', 'Mountain Climbers'), ('Sit-ups', 'Sit-ups'), ('Leg Raises', 'Leg Raises')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Distance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_in_km', models.FloatField()),
                ('WorkoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distance_reports', to='WorkoutPlan.workoutplan')),
            ],
        ),
        migrations.CreateModel(
            name='progressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.FloatField()),
                ('WorkoutPlan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='WorkoutPlan.workoutplan')),
            ],
        ),
    ]
