# Generated by Django 5.2.7 on 2025-12-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0008_alter_exercise_workout_list_distance_progressreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('detail', models.TextField()),
            ],
        ),
    ]
