# Generated by Django 5.2.7 on 2025-12-02 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0009_userlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userlist',
        ),
    ]
