# Generated by Django 5.2.8 on 2025-12-03 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0010_delete_userlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_percentage',
            field=models.FloatField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together={('user', 'WorkoutPlan')},
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='WorkoutPlan.exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to=settings.AUTH_USER_MODEL)),
                ('workout_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_exercises', to='WorkoutPlan.workoutplan')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('user', 'workout_plan', 'exercise')},
            },
        ),
    ]
