# Generated by Django 5.2.7 on 2025-12-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0011_progressreport_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='Workout_list',
            field=models.CharField(choices=[('Pullup', 'Pullup'), ('Pushup', 'Pushup'), ('Plank', 'Plank'), ('Squat', 'Squat'), ('Lunges', 'Lunges'), ('Jumping Jacks', 'Jumping Jacks'), ('High Knees', 'High Knees'), ('Sit-ups', 'Sit-ups'), ('Leg Raises', 'Leg Raises')], max_length=50, null=True),
        ),
    ]
