# Generated by Django 5.2.8 on 2025-12-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0012_alter_exercise_workout_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='Workout_list',
        ),
        migrations.AddField(
            model_name='exercise',
            name='Workout_list',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='WorkoutPlan.workouttype'),
        ),
    ]
