# Generated by Django 5.2.8 on 2025-12-03 17:13

from django.db import migrations

def populate_workout_types(apps, schema_editor):
    WorkoutType = apps.get_model('WorkoutPlan', 'WorkoutType')
    workout_types = [
        'Pullup',
        'Pushup',
        'Plank',
        'Squat',
        'Lunges',
        'Jumping Jacks',
        'High Knees',
        'Mountain Climbers',
        'Sit-ups',
        'Leg Raises',
    ]
    for workout_type in workout_types:
        WorkoutType.objects.get_or_create(name=workout_type)

def reverse_populate(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0013_workouttype_remove_exercise_workout_list_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_workout_types, reverse_populate),
    ]
