# Generated by Django 5.2.8 on 2025-12-03 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0014_auto_20251204_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='Workout_list',
        ),
        migrations.DeleteModel(
            name='WorkoutType',
        ),
        migrations.AddField(
            model_name='exercise',
            name='Workout_list',
            field=models.CharField(choices=[('Pullup', 'Pullup'), ('Pushup', 'Pushup'), ('Plank', 'Plank'), ('Squat', 'Squat'), ('Lunges', 'Lunges'), ('Jumping Jacks', 'Jumping Jacks'), ('High Knees', 'High Knees'), ('Mountain Climbers', 'Mountain Climbers'), ('Sit-ups', 'Sit-ups'), ('Leg Raises', 'Leg Raises')], max_length=50, null=True),
        ),
    ]
