# Generated by Django 5.2.8 on 2025-12-03 17:29

from django.db import migrations


def populate_user_from_workout_plan(apps, schema_editor):
    ProgressReport = apps.get_model('WorkoutPlan', 'progressReport')
    WorkoutPlan = apps.get_model('WorkoutPlan', 'WorkoutPlan')
    for report in ProgressReport.objects.filter(user__isnull=True):
        if hasattr(report, 'WorkoutPlan') and report.WorkoutPlan:
            if hasattr(report.WorkoutPlan, 'user') and report.WorkoutPlan.user:
                report.user = report.WorkoutPlan.user
                report.save()
        elif hasattr(report, 'workout_plan') and report.workout_plan:
            if hasattr(report.workout_plan, 'user') and report.workout_plan.user:
                report.user = report.workout_plan.user
                report.save()


def reverse_populate(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0015_remove_exercise_workout_list_delete_workouttype_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_user_from_workout_plan, reverse_populate),
    ]
