# Generated by Django 5.2.7 on 2025-12-03 17:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutPlan', '0016_set_default_user_for_progress_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distance',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='progressreport',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='workoutplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='distance',
            old_name='WorkoutPlan',
            new_name='workout_plan',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Coordinates',
            new_name='coordinates',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='WorkoutPlan',
            new_name='workout_plan',
        ),
        migrations.RenameField(
            model_name='progressreport',
            old_name='WorkoutPlan',
            new_name='workout_plan',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='WorkoutPlan',
            new_name='exercises',
        ),
        migrations.AlterUniqueTogether(
            name='progressreport',
            unique_together={('user', 'workout_plan')},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='workout_plan',
        ),
        migrations.AddField(
            model_name='distance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workout_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='distance',
            name='distance_in_km',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='Workout_list',
            field=models.CharField(blank=True, choices=[('Pullup', 'Pullup'), ('Pushup', 'Pushup'), ('Plank', 'Plank'), ('Squat', 'Squat'), ('Lunges', 'Lunges'), ('Jumping Jacks', 'Jumping Jacks'), ('High Knees', 'High Knees'), ('Mountain Climbers', 'Mountain Climbers'), ('Sit-ups', 'Sit-ups'), ('Leg Raises', 'Leg Raises')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='calories_burned',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='reps',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='rest_time',
            field=models.PositiveIntegerField(help_text='Rest time in seconds'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sets',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='progressreport',
            name='progress_percentage',
            field=models.FloatField(default=0.0, editable=False),
        ),
    ]
