# Generated by Django 5.2.7 on 2025-11-13 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0003_note_delete_goalreminder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoalProgress',
        ),
    ]
