# Generated by Django 5.2.7 on 2025-12-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Goal', '0004_delete_goalprogress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
